Repository Salary-Dev/Salary_FE, pull requests merged in 2024-12, with the labels that each got.

#45 Fix/#8/modifying recoil auth token
  App.js
  components/homeScreen/Home_Article_List.js
  screens/HomeScreen.js
  screens/SignInScreen.js
Labels: 🔨 Refactor

#46 닉네임 조회, 수정 api 추가
  Recoil/nicknameState.js
  components/vocaListScreen/VocaReminder_Loader.js
  screens/HomeScreen.js
  screens/MyPageNicknameChangeScreen.js
  screens/MyPageScreen.js
  screens/TodaySalaryEduScreen.js
  screens/TodayTrendQuizScreen.js
  screens/TodayTrendSolutionScreen.js
  screens/VocaListScreen.js
  screens/VocaSearchScreen.js
Labels: 📬 API

#47 [MyPageScreen] seedhistoryscreen 구현
  components/homeScreen/Home_Article.js
  components/homeScreen/Home_Article_List.js
  components/myPageScreen/DatePicker.js
  package.json
  screens/MyPageScreen.js
  screens/MyPageSeedHistoryScreen.js
  screens/SignInScreen.js
  screens/TodaySalaryQuizScreen.js
  services/fetchTodayAttendanceDetail.js
  services/fetchTodayAttendanceState.js
  yarn.lock
Labels: 📬 API, ✨ Feature

#49 My page screen/#6/adding toast
  App.js
  common/Toast.js
  screens/MyPageNicknameChangeScreen.js
  screens/MyPageScreen.js
  screens/SignInScreen.js
  screens/SignUpScreen.js
Labels: 🎨 Html&css, ✨ Feature

#50 [TodaySalaryEduScreen] Word Data API 수정
  assets/img/vocaListScreen/emptyBox.png
  screens/HomeScreen.js
  screens/MyPageNicknameChangeScreen.js
  screens/TodaySalaryEduScreen.js
  screens/VocaListScreen.js
  services/fetchTodayWordData.js
  services/fetchTodayWordId.js
Labels: 📬 API

#52 feat: 뉴스레터 최종 퍼블리싱
  App.js
  assets/img/NewsLetterMainScreen/BlueCheck.png
  assets/img/NewsLetterMainScreen/Hamburger.png
  components/NewsLetterMainScreen/ArrivedLetterList.js
  components/NewsLetterMainScreen/CustomDrawer.js
  components/NewsLetterMainScreen/SubscribingLetterList.js
  gesture-handler.js
  gesture-handler.native.js
  package.json
  screens/NewsLetterArticleScreen.js
  screens/NewsLetterMainScreen.js
  yarn.lock
Labels: 🎨 Html&css, ✨ Feature
