Repository Salary-Dev/Salary_FE, pull requests merged in 2024-10, with the labels that each got.

#5 [BottomTab] bottomTab 아이콘 색상 변경 및 코드 구조 변경
  App.js
Labels: 🎨 Html&css, 🔨 Refactor

#6 chore: feat/SpalshScreen 최신화
  App.js
  assets/SignInCharacter.png
  assets/SignInText_SALARY.png
  pull_request_template.md
  screens/SignInScreen.js
  screens/SplashScreen.js
Labels: 📃 Docs

#7 chore: Splash screen/#1/splash animation를 feat/SpalshScreen으로 merge
  assets/SplashShadow.png
  assets/animations/Salary_Splash.json
  package.json
  screens/SplashScreen.js
  yarn.lock
Labels: ⚙ Setting
